//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtekKurumsal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AltÖzellikler
    {
        public int AltÖzellikId { get; set; }
        public Nullable<int> ÖzellikId { get; set; }
        public string AltÖzellikAdi { get; set; }
    }
}
