//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtekKurumsal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class KurumsalSiteAtekEntities : DbContext
    {
        public KurumsalSiteAtekEntities()
            : base("name=KurumsalSiteAtekEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AltÖzellikler> AltÖzellikler { get; set; }
        public DbSet<Blog> Blog { get; set; }
        public DbSet<Haberler> Haberler { get; set; }
        public DbSet<İletisim> İletisim { get; set; }
        public DbSet<Kategori> Kategori { get; set; }
        public DbSet<Logo> Logo { get; set; }
        public DbSet<Markalar> Markalar { get; set; }
        public DbSet<Özellikler> Özellikler { get; set; }
        public DbSet<Sayfalar> Sayfalar { get; set; }
        public DbSet<SayfaResimleri> SayfaResimleri { get; set; }
        public DbSet<Slider> Slider { get; set; }
        public DbSet<SSS> SSS { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Ürün> Ürün { get; set; }
        public DbSet<ÜrünKategori> ÜrünKategori { get; set; }
        public DbSet<ÜrünÖzellik> ÜrünÖzellik { get; set; }
    
        public virtual ObjectResult<HaberListele_Result> HaberListele()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HaberListele_Result>("HaberListele");
        }
    
        public virtual ObjectResult<MarkaListele_Result> MarkaListele()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MarkaListele_Result>("MarkaListele");
        }
    }
}
