//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtekKurumsal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sayfalar
    {
        public int SayfaId { get; set; }
        public string SayfaAd { get; set; }
        public string SayfaBaslik { get; set; }
        public string Sayfaİcerik { get; set; }
        public Nullable<bool> GosterilsinMi { get; set; }
    }
}
