//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtekKurumsal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ürün
    {
        public int ÜrünId { get; set; }
        public int KategoriId { get; set; }
        public string ÜrünAdi { get; set; }
        public string ÜrünAciklama { get; set; }
        public string Resim { get; set; }
        public string VideoUrl { get; set; }
        public string ÜrünKodu { get; set; }
    }
}
